# Статистичні методи
Індивідуальне завдання 5

Токарєв Павло, МФ-51

## Вхідні дані

In [29]:
import numpy as np

n,k,m = 20, 3, 12

unknown = np.array([0.171, 0.2185, 0.2299, 0.2515, 0.5925, 0.7015, 0.9305, 1.3655, 2.1375, 2.3925, 2.4652, 2.6182, 2.7822, 2.9352, 3.0802, 3.4802, 3.8362, 4.0982, 4.098932, 4.277932])

data = np.array([
    0.2522, 0.4701, 0.0114, 0.676, 1.114, 0.7842, 0.326, 0.8458, 0.5651, 0.4874, 0.4541, 0.2715, 0.07362, -0.3739, -0.3704, -1.583, -0.8576, -0.9874, -1.121, -1.377,
0.6442, 0.8189, 1.278, 0.6537, 0.7007, 0.8685, 0.8693, 0.355, 0.3473, 0.1856, 0.2726, -0.8755, -0.2545, -0.287, -0.8144, -1.57, -0.8964, -1.188, -0.7697, -1.035,
-0.9576, -0.6482, -0.0671, -0.829, -0.6153, -0.2497, 0.4387, 0.4246, 0.4726, 1.26, 1.095, 0.6203, 0.91, 1.207, 1.739, 1.022, 1.03, 1.422, 0.7135, 1.431,
0.8231, 1.077, 0.7343, 0.5571, 0.3947, 0.5468, 0.3649, 1.08, 0.5626, 0.195, 0.2991, -0.131, -0.04538, -0.2288, -0.378, -0.936, -1.498, -0.9872, -0.6607, -0.3869,
-0.0967, 0.4055, 0.2321, 0.5628, 0.3636, 0.969, 1.299, 0.336, 0.4749, 0.1269, -0.04619, -0.0736, -0.3103, -0.3999, -0.2117, -1.558, -1.264, -1.175, -0.5296, -0.3691,
-0.9166, -0.6159, -0.6002, -0.357, 0.4701, 0.2585, 0.7673, 0.0309, 1.277, 1.296, 0.2035, 1.192, 0.9688, 0.8937, 0.8683, 0.7634, 1.368, 0.5969, 0.927, 1.219,
0.2311, 0.1716, -0.031, 0.4236, -0.0383, 1.042, 0.9297, 0.9014, 0.1643, 0.4055, 0.3709, -0.04486, -0.1103, 0.4959, -0.0021, -0.3953, -1.334, -0.8491, -1.488, -0.8533,
-0.0159, -0.0182, 0.1981, -0.1947, 0.8678, 1.454, 0.7554, 1.366, 0.0976, 0.1505, -0.2332, -0.1341, -1.257, -0.4495, -0.8346, -0.7739, -0.6936, 0.004, -0.8951, -0.7135,
-0.4012, -0.5226, -0.6268, -0.5035, -0.5665, -0.0507, 0.2452, 0.4128, 0.9378, 0.9365, 0.7134, 1.037, 0.916, 1.393, 1.422, 1.023, 0.6274, 0.8096, 0.5129, 0.9963,
-0.3112, 0.5858, 0.7402, 0.5037, 0.9679, 0.0171, 1.347, 1.209, 0.3042, -0.1918, -0.0481, 0.1527, 0.2412, -0.7997, -0.237, -1.34, -0.6077, -1.267, -0.9614, -0.9729,
0.1656, 0.5874, 0.6378, 0.2624, 0.6094, 0.4926, 1.075, 0.8251, 0.1533, 0.5507, -0.3627, 0.0041, 0.0284, -0.1765, -1.124, -1.127, -1.075, -1.604, -1.54, -1.038,
-0.0576, -0.5979, -0.5625, -0.1301, -0.9347, -0.4553, -0.6689, 0.4776, 1.356, 0.8776, 1.449, 0.7871, 1.165, 0.7177, 0.8893, 1.573, 0.9312, 0.4496, 0.5985, 0.8867,
1.076, 0.3531, 0.7671, 0.211, 0.7156, 0.2808, 0.8619, 0.9565, 0.5778, 1.046, 0.1021, 0.6599, -0.325, 0.2058, -0.4903, -0.5009, -0.6054, -0.7271, -0.5694, -1.231,
0.7772, 0.4722, -0.0614, 0.4376, 0.3046, 1.037, 1.351, 1.318, 0.0146, -0.1493, -0.6884, -0.1375, -0.7085, -0.5854, -1.235, -0.9408, -0.8148, -0.5372, -0.8101, -0.8427,
-0.3237, -0.8618, -0.0938, -1.148, -0.7342, 0.2847, 0.3848, 0.5453, 0.8963, 1.25, 1.405, 0.6373, 0.7782, 1.66, 1.184, 1.135, 1.128, 0.317, 1.066, 0.8891,
0.1173, 0.6992, 0.6728, 0.128, 0.6504, 0.4683, 0.5617, 0.9723, 0.2095, 0.0719, -0.0535, 0.1752, 0.2433, -0.2312, -0.5755, -1.374, -1.334, -0.7458, -1.545, -1.069,
0.2482, 0.9891, 0.3998, 1.047, 0.8049, 1.432, 0.6609, 1.166, -0.1577, -0.449, -0.7419, -0.2104, 0.4277, -0.6544, -0.2397, -0.9329, -1.059, -0.6197, -1.458, -0.7527,
-1.017, -0.6243, -0.6774, -0.6424, -0.3739, -0.753, -0.3852, 0.6095, 0.6395, 0.7232, 1.193, 0.9004, 1.136, 1.145, 1.117, 1.144, 1.13, 0.4781, 0.7373, 0.3241,
0.3938, 0.389, 0.7379, 0.802, 0.373, 0.3943, 1.517, 0.7112, 0.6586, 0.5281, 0.2348, 0.08208, -0.6171, 0.1835, -0.5087, -0.8391, -0.8179, -1.219, -0.7712, -1.332,
0.7088, 0.5006, 0.7104, -0.3122, 0.9821, 0.0088, 0.3445, 0.8271, 0.8588, 0.6057, -0.07606, -0.3695, -1.117, -0.8647, -0.3013, -1.426, -1.407, -0.3984, -0.9692, -1.201,
-0.9031, 0.079, -0.1162, -0.9414, -0.4781, -0.5615, -0.279, 0.3726, 1.145, 1.012, 0.53, 1.198, 0.8045, 0.462, 0.9998, 0.1303, 0.5167, 0.7702, 1.058, 1.073,
0.5532, 0.3286, 0.5252, 0.5063, 0.3534, 0.3, 1.204, 0.2386, 0.022, 0.079, 0.0426, 0.00925, -0.03747, -0.5245, -0.4876, -0.4953, -0.5, -1.009, -0.4924, -1.114,
-0.236, 0.9699, 0.8871, 0.4538, 0.4862, 1.037, 0.9459, 1.039, 0.2328, -0.1199, -0.3462, -0.5321, -0.2201, -1.321, -0.5877, -1.193, -1.341, -0.9834, -1.254, -1.052,
-0.1325, -0.0496, -0.155, 0.115, 0.0029, -0.0544, 0.03072, 0.3066, 0.7038, 1.73, 0.8617, 0.9251, 1.202, 0.8177, 1.412, 0.9121, 1.223, 0.8338, 0.4522, 0.1815,
1.248, 0.0605, 0.869, -0.2623, 0.9069, 0.6309, 0.2538, 0.7581, 0.1478, 0.017, 0.6018, 0.15, 0.2378, -0.5896, -0.1834, -0.8547, -0.7607, -0.8509, -0.5132, -1.079,
0.618, -0.2325, 0.4566, 0.5127, 1.111, 0.8954, 1.593, 0.4625, 0.2132, -0.01991, -0.1889, 0.1054, 0.1681, -0.3039, -0.998, -0.9572, -0.5711, -1.33, -1.259, -0.7217,
0.1245, -0.5892, -0.4118, -0.3929, -0.8215, -0.2435, -0.1559, 0.0119, 0.4803, 0.5949, 0.7368, 0.959, 1.55, 0.9036, 1.706, 1.231, 1.453, 0.8464, 0.557, 0.9201,
-0.1065, -0.141, 0.5483, 0.6951, 1.131, 0.756, 0.758, 0.2822, -0.2821, 0.5446, 0.4457, 0.4032, -0.09183, -0.9707, -0.3986, -0.4347, -1.024, -0.6848, -1.03, -1.624,
0.1235, 0.0513, 0.2783, -0.0059, 0.6143, 1.227, 0.436, 1.32, -0.0166, -0.1027, -0.5535, 0.0508, -0.4603, -0.1177, -0.8986, -1.27, -1.366, -0.7939, -0.8387, -0.5829,
-0.5347, -0.3376, -0.9562, -0.4336, -0.6766, -0.1479, -0.3712, 0.7515, 0.4343, 1.613, 0.903, 1.232, 0.9334, 0.7527, 1.152, 1.335, 0.8927, 0.7756, 0.8337, 0.6687,
0.2045, -0.1014, -0.0768, 0.4795, 1.029, 0.3921, 1.257, 1.324, 0.0319, 0.3155, 0.4276, -0.1416, -0.475, 0.3583, -0.2855, -1.036, -0.4853, -1.76, -1.036, -1.31,
0.2873, 0.7687, 0.865, 0.5181, 1.073, 1.166, 1.27, 0.9333, 0.4609, -0.3559, 0.0641, -0.2957, -1.026, -0.4651, -0.477, -0.7655, -0.913, -1.037, -0.5186, -0.7531,
-0.7011, -0.5679, -0.5175, -0.3994, 0.049, 0.1101, 0.3336, 0.9459, 0.6486, 0.7652, 1.031, 0.2019, 0.785, 1.666, 0.7194, 1.643, 1.757, 1.659, 0.7068, 1.282,
-0.2822, 0.1527, 1.332, 0.1689, 0.3414, 1.006, 0.8237, 1.091, 0.3237, 0.5331, 0.2337, 0.1143, 0.1211, -0.2046, -0.5597, -0.6974, -1.169, -0.8476, -1.121, -1.018,
0.5303, 0.2319, 0.6419, 0.5234, 0.9228, 0.7336, 0.5104, 0.8331, 0.1123, -0.02634, 0.1901, -0.007, -0.3995, -0.4038, -1.221, -0.6846, -1.15, -1.516, -0.62, -0.9536,
-1.05, -0.4704, -0.3491, -0.4942, 0.0864, -0.3547, -0.1447, 0.1922, 0.5503, 0.908, 0.9784, 1.461, 0.842, 0.2176, 1.201, 1.788, 1.228, 0.5749, 0.5482, 0.7941,

], dtype=float, ).reshape((m, k, n))

## Середнє

In [30]:
def mean() -> np.array:
    return sum(data[i] for i in range(m))/m

M = mean()
M

array([[ 0.34994167,  0.3371    ,  0.5692    ,  0.40740833,  0.66158333,
         0.55154167,  0.85039167,  0.864175  ,  0.27378333,  0.33594167,
         0.25923333,  0.1417225 , -0.06542167, -0.22329167, -0.37306667,
        -0.87386667, -0.91613333, -0.994575  , -0.94244167, -1.113925  ],
       [ 0.312875  ,  0.46206667,  0.54364167,  0.37155833,  0.7367    ,
         0.94340833,  0.92586667,  0.898425  ,  0.23261667,  0.03302917,
        -0.22585417, -0.20625833, -0.42741667, -0.50240833, -0.74525   ,
        -1.09990833, -1.04590833, -0.93155   , -0.95516667, -0.83460833],
       [-0.57255   , -0.48386667, -0.4278    , -0.51304167, -0.3827    ,
        -0.18478333,  0.016285  ,  0.42345   ,  0.795125  ,  1.08053333,
         0.92498333,  0.92925833,  0.99924167,  0.98633333,  1.20081667,
         1.14165   ,  1.10708333,  0.794425  ,  0.725925  ,  0.8888    ]])

## Коваріаційні матриці

In [31]:
def matrix() -> np.array:
    return sum(
        np.array([
        (data[i, :, j]-M[:, j]).reshape(k,1)
            .dot((data[i, :, j]-M[:, j]).reshape(1,k))
                         for j in range(n)
        ])
               for i in range(m)
               )/(m-1)

CO = matrix()
CO[14] #t15

array([[ 0.02922949, -0.01294765,  0.01087533],
       [-0.01294765,  0.14035788, -0.04144897],
       [ 0.01087533, -0.04144897,  0.10253116]])

In [32]:
CO

array([[[ 0.24952622,  0.03590664,  0.0729344 ],
        [ 0.03590664,  0.11472761, -0.02199573],
        [ 0.0729344 , -0.02199573,  0.1686666 ]],

       [[ 0.11999036,  0.05467569, -0.01630031],
        [ 0.05467569,  0.15566304,  0.00924847],
        [-0.01630031,  0.00924847,  0.06969415]],

       [[ 0.17251542, -0.04658006,  0.00739701],
        [-0.04658006,  0.1352774 ,  0.04289725],
        [ 0.00739701,  0.04289725,  0.07787675]],

       [[ 0.08905181, -0.05521868, -0.00222247],
        [-0.05521868,  0.1445945 ,  0.01047406],
        [-0.00222247,  0.01047406,  0.11843285]],

       [[ 0.14171991,  0.00301438, -0.06553265],
        [ 0.00301438,  0.07191257, -0.01154023],
        [-0.06553265, -0.01154023,  0.18969251]],

       [[ 0.09351027,  0.04132231,  0.00167331],
        [ 0.04132231,  0.1614752 ,  0.0410715 ],
        [ 0.00167331,  0.0410715 ,  0.10133707]],

       [[ 0.17699817, -0.05379563, -0.06436186],
        [-0.05379563,  0.1599217 ,  0.07283293],
        

## Коваріаційні функції

In [33]:
def cofunction() -> np.array:
    return sum(np.array([
        np.array([
        (data[i, :, j]-M[:, j]).reshape(k,1)
            .dot((data[i, :, s]-M[:, s]).reshape(1,k))
                         for j in range(n)
        ]) for s in range(n)])
               for i in range(m)
               )/(m-1)

COF = cofunction()
COF[7][5] == COF[5][7].T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
COF

array([[[[ 2.49526215e-01,  3.59066375e-02,  7.29343959e-02],
         [ 3.59066375e-02,  1.14727606e-01, -2.19957277e-02],
         [ 7.29343959e-02, -2.19957277e-02,  1.68666599e-01]],

        [[ 2.45839482e-02, -2.31549945e-02, -4.09457709e-02],
         [-3.93764285e-02, -1.85500891e-02, -5.32630436e-02],
         [-2.29854542e-02, -1.88645291e-02, -4.25082091e-03]],

        [[ 9.04438727e-03,  3.39684636e-02, -1.54928182e-04],
         [-5.77262037e-02,  1.03054457e-02, -3.05324950e-02],
         [ 5.31284191e-02,  4.95092327e-02, -6.20942727e-04]],

        ...,

        [[ 2.68375789e-02,  5.04766614e-03,  3.93333318e-03],
         [ 3.94568414e-02, -5.75864318e-03, -2.02647200e-02],
         [-1.14944093e-02,  4.70767068e-03, -2.47591777e-02]],

        [[ 1.17279660e-01,  1.37901407e-02,  6.94382223e-02],
         [ 1.11195239e-02,  1.44383100e-02, -7.26819236e-02],
         [ 2.93948889e-02,  3.01011989e-02, -3.12290495e-02]],

        [[ 3.38663466e-02, -4.56213207e-02, -2