# Статистичні методи
Індивідуальне завдання 3(B)

Токарєв Павло, МФ-51

## Вхідні дані

In [25]:
N = 4
M = 8

import numpy as np
A = np.array([0.3432, 0.4382, 0.1013, 0.1174,
              0.0522, 0.4995, 0.4016, 0.0467,
              0.2966, 0.0331, 0.4173, 0.2531,
              0.2616, 0.1974, 0.3512, 0.1897,])\
    .reshape(N,N)

B = np.array([0.1220, 0.0626, 0.1789, 0.0155, 0.1142, 0.2100, 0.2205, 0.0763,
              0.1574, 0.0489, 0.1684, 0.1164, 0.1187, 0.0816, 0.1648, 0.1439,
              0.1569, 0.0714, 0.1722, 0.1665, 0.0386, 0.1947, 0.0171, 0.1825,
              0.1900, 0.1871, 0.2042, 0.0159, 0.1904, 0.0869, 0.0201, 0.1053,
])\
    .reshape(N,M)

P = [0.2741, 0.3051, 0.2858, 0.1350]
O = np.array([6, 5, 5, 7, 6, 8, 2, 7, 6, 4, 1, 8, 7, 1, 8, 3, 7, 2, 2, 4, 3, 7, 1, 8, 8, 3, 5, 1, 4, 5])

In [26]:
A

array([[0.3432, 0.4382, 0.1013, 0.1174],
       [0.0522, 0.4995, 0.4016, 0.0467],
       [0.2966, 0.0331, 0.4173, 0.2531],
       [0.2616, 0.1974, 0.3512, 0.1897]])

In [27]:
B

array([[0.122 , 0.0626, 0.1789, 0.0155, 0.1142, 0.21  , 0.2205, 0.0763],
       [0.1574, 0.0489, 0.1684, 0.1164, 0.1187, 0.0816, 0.1648, 0.1439],
       [0.1569, 0.0714, 0.1722, 0.1665, 0.0386, 0.1947, 0.0171, 0.1825],
       [0.19  , 0.1871, 0.2042, 0.0159, 0.1904, 0.0869, 0.0201, 0.1053]])

In [28]:
P

[0.2741, 0.3051, 0.2858, 0.135]

In [29]:
O

array([6, 5, 5, 7, 6, 8, 2, 7, 6, 4, 1, 8, 7, 1, 8, 3, 7, 2, 2, 4, 3, 7,
       1, 8, 8, 3, 5, 1, 4, 5])

In [30]:
D0 = [P[i]*B[i, O[0]-1] for i in range(N)]
D0

[0.057561, 0.02489616, 0.05564526, 0.0117315]

In [31]:
PSI0 = [0 for _ in range(N)]
PSI0

[0, 0, 0, 0]

## Обчислення дельта та псі

In [32]:
from typing import List

def next_delta(delta: List[float], t: int) -> List[float]:
    return [max([delta[i]*A[i,j] for i in range(N)])*B[j, O[t]-1] for j in range(N)]

def next_psi(delta: List[float], t: int) -> List[float]:
    return [np.array([delta[i]*A[i,j] for i in range(N)]).argmax() for j in range(N)]

D = D0
PSI = PSI0
APSI = [PSI0]
for i in range(len(O)-1):
    PSI = next_psi(D, i+1)
    APSI.append(PSI)
    print(D)
    D = next_delta(D, i+1)
print(D)

[0.057561, 0.02489616, 0.05564526, 0.0117315]
[0.00225601359984, 0.0029939974247399997, 0.0008963216061228001, 0.0026815584342624]
[8.842093366451305e-05, 0.00017751605341116065, 4.641222951893754e-05, 9.685488730011152e-05]
[6.691307207622224e-06, 1.461269547827856e-05, 1.2190666445536684e-06, 3.6930477962870626e-07]
[4.822558930677489e-07, 5.956017775382515e-07, 1.1425888707437275e-06, 6.826511761059439e-08]
[2.5857448846475585e-08, 4.281069434598332e-08, 8.701642627644774e-08, 3.0451627307405505e-08]
[1.6156479093030094e-09, 1.0456747552825328e-09, 2.5926735645205413e-09, 4.120663736485445e-09]
[2.3769142217894263e-10, 1.3405145475675098e-10, 2.474672848273807e-11, 1.5711967207306908e-11]
[1.713089617928075e-11, 8.499160705823114e-12, 1.0481687005641592e-11, 2.4249421505549037e-12]
[9.112951531530189e-14, 8.737867133505601e-13, 7.282723299111303e-13, 4.21813481999334e-14]
[2.635267991230023e-14, 6.869824732634839e-14, 5.5058209546400677e-14, 3.5021888073096343e-14]
[1.24599921579658

## Результати
### Вірогідність $P^*$

In [33]:
p = max(D)
p

2.8587598025631146e-36

### Останній елемент $q^*_T$

In [34]:
q = np.array(D[::-1]).argmax()
q

2

### Стани послідовності ($Q$)

In [35]:
Q = [q]
for i in range(len(O)-1, 0, -1):
    q = APSI[i][q-1]+1
    Q.append(q)
Q = Q[::-1]
Q

[1,
 2,
 2,
 2,
 3,
 3,
 4,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 4,
 3,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

### Вірогідність послідовності ($\overline{P^*}$)

In [36]:
def probability(trace: List[int]) -> float:
    t = trace[0]-1
    result = P[t]*B[t, O[0]-1]
    for i in range(len(trace)-1):
        qi = trace[i]-1
        qip = trace[i+1]-1
        result *= A[qi, qip] * B[qip, O[i+1]-1]
    return result

probability(Q)

2.858759802563114e-36