# Статистичні методи
Індивідуальне завдання 3(A)

Токарєв Павло, МФ-51

## Вхідні дані

In [62]:
import numpy as np

N = 8
M = 4

A = np.array([0.1391,	0.1208,	0.0976,	0.0639,	0.1116,	0.1694,	0.1696,	0.1281,
              0.2664,	0.2300,	0.0439,	0.1797,	0.1237	,0.0328,	0.0527,	0.0706,
              0.1759,	0.1129,	0.1817,	0.0672,	0.0026,	0.1392,	0.0731,	0.2475,
              0.2102,	0.0911,	0.0058,	0.1557,	0.1942	,0.2253,	0.0132	,0.1045,
              0.1313,	0.1548,	0.1621	,0.1465,	0.1638,	0.0843,	0.1311	,0.0262,
              0.0160,	0.2722,	0.0791,	0.1653,	0.2673,	0.0516,	0.0536,	0.0949,
              0.3022,	0.1266,	0.0885,	0.0492,	0.1287,	0.1214,	0.0425,	0.1409,
              0.0275,	0.1844,	0.0033,	0.1720,	0.2370,	0.0706,	0.1344,	0.1708,
])\
    .reshape(N,N)
B = np.array([0.0432,0.3492,0.4519,  0.1557,
              0.2648,	0.3073,	0.2678,	0.1601,
              0.1256,	0.3363,	0.1067,	0.4313,
              0.4181,	0.4046,	0.1164,	0.0609,
              0.0937,	0.3151,	0.3344,	0.2568,
              0.3097,	0.0982,	0.2460,	0.3462,
              0.2240,	0.5482,	0.0499,	0.1780,
              0.2758,	0.0327,	0.3914,	0.3001,
])\
    .reshape(N,M)
P = np.array([0.1141, 0.1789, 0.1851, 0.1701, 0.0685, 0.0975, 0.1621, 0.0237])
O = np.array([1, 3, 2, 1, 1, 1, 4, 4, 4, 3, 1, 2, 1, 1, 2, 3])

In [63]:
A

array([[0.1391, 0.1208, 0.0976, 0.0639, 0.1116, 0.1694, 0.1696, 0.1281],
       [0.2664, 0.23  , 0.0439, 0.1797, 0.1237, 0.0328, 0.0527, 0.0706],
       [0.1759, 0.1129, 0.1817, 0.0672, 0.0026, 0.1392, 0.0731, 0.2475],
       [0.2102, 0.0911, 0.0058, 0.1557, 0.1942, 0.2253, 0.0132, 0.1045],
       [0.1313, 0.1548, 0.1621, 0.1465, 0.1638, 0.0843, 0.1311, 0.0262],
       [0.016 , 0.2722, 0.0791, 0.1653, 0.2673, 0.0516, 0.0536, 0.0949],
       [0.3022, 0.1266, 0.0885, 0.0492, 0.1287, 0.1214, 0.0425, 0.1409],
       [0.0275, 0.1844, 0.0033, 0.172 , 0.237 , 0.0706, 0.1344, 0.1708]])

In [64]:
B

array([[0.0432, 0.3492, 0.4519, 0.1557],
       [0.2648, 0.3073, 0.2678, 0.1601],
       [0.1256, 0.3363, 0.1067, 0.4313],
       [0.4181, 0.4046, 0.1164, 0.0609],
       [0.0937, 0.3151, 0.3344, 0.2568],
       [0.3097, 0.0982, 0.246 , 0.3462],
       [0.224 , 0.5482, 0.0499, 0.178 ],
       [0.2758, 0.0327, 0.3914, 0.3001]])

In [65]:
P

array([0.1141, 0.1789, 0.1851, 0.1701, 0.0685, 0.0975, 0.1621, 0.0237])

In [66]:
O

array([1, 3, 2, 1, 1, 1, 4, 4, 4, 3, 1, 2, 1, 1, 2, 3])

## Ініціазація індукції

In [68]:
I = [P[i]*B[i, O[0]-1] for i in range(N)]
I

[0.00492912,
 0.04737272,
 0.023248559999999998,
 0.07111881,
 0.006418450000000001,
 0.030195749999999997,
 0.0363104,
 0.006536459999999999]

## Індукційний перехід

In [69]:
from typing import List
def next(prev: List[float], t: int) -> List[float]:
    return [sum([prev[i]*A[i,j] for i in range(N)])*B[j, O[t]-1] for j in range(N)]

R = I
for i in range(len(O)-1):
    R = next(R, i+1)
    print(R)

[0.0202554950731339, 0.009536338821503, 0.0014790169559285998, 0.0035275897307963998, 0.0119135918876656, 0.00703973729196, 0.0005415348769157, 0.0103439862632588]
[0.002962850376211389, 0.0033388132923186068, 0.0017672149504017257, 0.0033870930481966328, 0.003303335140557051, 0.000678396229560709, 0.00408136333301492, 0.0002232084524306746]
[0.00017316810254383236, 0.0007646889361658993, 0.00021698219004013855, 0.00094938407868939, 0.00025361095059766637, 0.0007572910564770836, 0.0003416524961724009, 0.0005986827986224041]
[2.7244315537179934e-05, 0.0001871678573190424, 2.8715563697022035e-05, 0.0002479321744234381, 6.827694083066433e-05, 0.00013710910423509696, 5.978203403888013e-05, 0.00012631336288154265]
[6.1998855133138825e-06, 3.99634271895763e-05, 5.671079271986092e-06, 5.570830560700869e-05, 1.4980705360471458e-05, 3.0851216540453015e-05, 1.2470886792513852e-05, 2.606811476307105e-05]
[4.851962478193224e-06, 5.244606211739086e-06, 4.214425687631128e-06, 1.7675703123078496e-06,

## Термінація та результат

In [70]:
sum(R)

1.2286286917000976e-10