# Статистичні методи
Індивідуальне завдання 3(B)

Токарєв Павло, МФ-51

## Вхідні дані

In [27]:
N = 4
M = 8

import numpy as np
A = np.array([0.3432, 0.4382, 0.1013, 0.1174,
              0.0522, 0.4995, 0.4016, 0.0467,
              0.2966, 0.0331, 0.4173, 0.2531,
              0.2616, 0.1974, 0.3512, 0.1897,])\
    .reshape(N,N)

B = np.array([0.1220, 0.0626, 0.1789, 0.0155, 0.1142, 0.2100, 0.2205, 0.0763,
              0.1574, 0.0489, 0.1684, 0.1164, 0.1187, 0.0816, 0.1648, 0.1439,
              0.1569, 0.0714, 0.1722, 0.1665, 0.0386, 0.1947, 0.0171, 0.1825,
              0.1900, 0.1871, 0.2042, 0.0159, 0.1904, 0.0869, 0.0201, 0.1053,
])\
    .reshape(N,M)

P = [0.2741, 0.3051, 0.2858, 0.1350]
O = np.array([6, 5, 5, 7, 6, 8, 2, 7, 6, 4, 1, 8, 7, 1, 8, 3, 7, 2, 2, 4, 3, 7, 1, 8, 8, 3, 5, 1, 4, 5])

In [28]:
A

array([[0.3432, 0.4382, 0.1013, 0.1174],
       [0.0522, 0.4995, 0.4016, 0.0467],
       [0.2966, 0.0331, 0.4173, 0.2531],
       [0.2616, 0.1974, 0.3512, 0.1897]])

In [29]:
B

array([[0.122 , 0.0626, 0.1789, 0.0155, 0.1142, 0.21  , 0.2205, 0.0763],
       [0.1574, 0.0489, 0.1684, 0.1164, 0.1187, 0.0816, 0.1648, 0.1439],
       [0.1569, 0.0714, 0.1722, 0.1665, 0.0386, 0.1947, 0.0171, 0.1825],
       [0.19  , 0.1871, 0.2042, 0.0159, 0.1904, 0.0869, 0.0201, 0.1053]])

In [30]:
P

[0.2741, 0.3051, 0.2858, 0.135]

In [31]:
O

array([6, 5, 5, 7, 6, 8, 2, 7, 6, 4, 1, 8, 7, 1, 8, 3, 7, 2, 2, 4, 3, 7,
       1, 8, 8, 3, 5, 1, 4, 5])

In [32]:
D0 = [P[i]*B[i, O[0]-1] for i in range(N)]
D0

[0.057561, 0.02489616, 0.05564526, 0.0117315]

In [33]:
PSI0 = [0 for _ in range(N)]
PSI0

[0, 0, 0, 0]

## Обчислення дельта та псі

In [34]:
from typing import List

def next_delta(delta: List[float], t: int) -> List[float]:
    return [max([delta[i]*A[i,j] for i in range(N)])*B[j, O[t]-1] for j in range(N)]

def next_psi(delta: List[float], t: int) -> List[float]:
    return [np.array([delta[i]*A[i,j] for i in range(N)]).argmax() for j in range(N)]

D = D0
PSI = PSI0
APSI = [PSI0]
for i in range(len(O)-1):
    PSI = next_psi(D, i+1)
    APSI.append(PSI)
    D = next_delta(D, i+1)

## Результати
### Вірогідність $P^*$

In [35]:
p = max(D)
p

2.8587598025631146e-36

### Останній елемент $q^*_T$

In [36]:
q = len(PSI) - np.array(PSI[::-1]).argmax()
q

4

### Стани послідовності ($Q$)

In [37]:
Q = [q]
for i in range(len(O)-1, 0, -1):
    q = APSI[i][q-1]+1
    Q.append(q)
Q = Q[::-1]
Q

[1,
 2,
 2,
 2,
 3,
 3,
 4,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 4,
 3,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 4]

### Вірогідність послідовності ($\overline{P^*}$)

In [38]:
def probability(trace: List[int]) -> float:
    t = trace[0]-1
    result = P[t]*B[t, O[0]-1]
    for i in range(len(trace)-1):
        qi = trace[i]-1
        qip = trace[i+1]-1
        result *= A[qi, qip] *B[qip, O[i+1]-1]
    return result

probability(Q)

2.672206484798075e-36