In [12]:
import numpy as np

n,k,m = 25, 3, 10

unknown = np.array([0.0856, 0.7656, 1.3396, 1.9056, 2.5016, 2.6986, 2.9166, 2.9397, 3.1887, 3.7137, 3.9437, 4.6537, 6.4737, 7.2837, 7.4277, 7.8747, 8.3497, 8.4485, 8.6535, 8.8605, 9.4015, 9.5025, 9.5762, 9.6647, 9.6895])

data = np.array([
    0.7532, 0.6916, 0.0291, -0.2289, -0.998, -0.9901, -1.043, -0.469, -0.0241, 0.6835, 0.763, 0.8589, -0.9924, 1.038, -0.1037, 0.2255, 0.8529, 0.2985, 1.057, -0.06241, -1.18, -0.6597, -1.196, -0.8856, -1.043,
-0.5445, 0.3736, 0.6044, 0.6372, 0.6475, 1.297, 1.058, 0.6213, 1.024, 0.7377, 0.7045, 0.4956, -0.9278, -0.988, -0.1617, -0.3001, -0.7796, -0.5934, -1.199, -1.272, -0.5313, -1.049, -1.382, -0.6596, -0.8982,
-0.7003, 0.2911, 1.077, 0.352, -0.6711, -0.3225, -1.275, -0.9397, -0.9861, -0.6497, -0.2593, 0.2719, -1.267, -0.5971, -0.3543, 0.0723, 1.254, 0.8218, 0.523, 0.7268, 0.5438, 0.4709, 0.1534, 0.1212, -0.1881,
0.1984, 1.073, 0.9395, -0.3283, -1.068, -0.6781, -0.1744, -0.4396, 0.1251, 0.3388, 1.494, 1.526, -0.1395, 0.591, 0.6419, 1.236, 0.7167, 0.419, 0.7106, -0.3271, -0.6078, -1.122, -1.123, -0.6046, -1.42,
-0.2941, 0.5978, 0.4784, 0.9926, 0.429, 0.8642, 0.7476, 0.9858, 1.654, 0.8256, 1.005, 0.7656, -0.0518, -0.6535, -1.023, -0.7016, -0.9201, -1.209, -1.543, -0.9227, -0.4645, -0.8358, -0.4419, -0.7545, -1.016,
-0.3841, 0.4394, 1.161, 0.6423, -0.8246, -0.9724, -0.8317, -0.8986, -0.9573, 0.1123, -0.3081, 0.4281, -0.2864, -0.8213, -0.5018, -0.0619, 0.931, 0.6764, 1.267, 0.4527, -0.1333, 0.1945, 0.9816, -0.9891, -0.231,
0.109, 0.6512, 0.2475, -1.263, -0.0812, -0.7754, -0.6613, -0.8052, -0.4579, 0.7757, 0.4611, 0.4203, -0.1078, -0.1357, 0.544, 0.7298, 1.067, 0.1312, 0.5799, 0.3971, -0.8409, -1.206, -0.3718, -1.119, -0.6484,
0.2554, 0.6578, -0.059, 1.257, 1.009, 1.102, 1.642, 1.645, 0.9308, 1.208, 1.003, 0.8767, 0.0287, -0.6269, -0.7584, -0.1128, -0.5694, -1.612, -1.455, -0.6887, -1.026, -0.8319, -1.129, -0.7735, -1.3,
-0.6266, 0.5887, 0.2984, 0.9622, -0.6872, -0.5191, -0.5878, -0.5702, -0.6699, -0.3019, -0.8796, 0.9307, -0.1881, -0.6432, -0.6711, -0.4724, 0.7524, 1.112, 0.425, 0.9529, 0.3136, 0.7404, 0.312, -0.3151, -0.2175,
0.3741, 0.2568, 0.0158, -0.6288, -0.5142, -0.7245, -0.7983, -0.3771, -0.7515, 0.1332, 0.9073, 1.161, -1.554, 0.8783, 0.9489, 1.096, 1.175, 0.8049, 0.2237, 0.4924, -0.6921, -0.9129, -0.2909, -0.3804, -1.197,
-0.2784, 0.4765, 0.4398, 1.068, 0.1922, 0.4423, 1.032, 1.302, 0.727, 1.048, 0.1562, 0.5419, -0.0467, -0.6644, -0.9361, -0.5759, -1.353, -0.444, -0.8153, -0.8269, -1.044, -1.381, -1.413, -0.9343, -1.56,
0.1206, 0.6301, 1.249, 0.3365, -0.2633, -0.0786, -1.222, -1.015, -1.017, -0.5494, 0.0768, 0.9512, -0.1837, -0.6372, -0.8172, -0.2463, 0.5375, 0.8996, 1.084, 2.016, 0.3322, 0.4002, 0.1066, 0.1848, -0.325,
0.0609, 1.115, 0.4006, -0.8163, -0.7383, -1.226, -0.549, -0.5939, 0.1487, 1.099, 0.7366, 1.137, -0.8931, 0.9926, 1.018, 1.113, 0.0207, 0.1316, 0.3414, -0.3842, -1.2, -0.6895, -1.136, -0.6782, -0.5238,
-0.4532, 0.2479, -0.0786, 1.038, 0.8722, 0.6167, 1.298, 0.6471, 0.1563, 0.5656, 0.8317, 0.2583, -0.5292, -1.378, -0.486, -0.6664, -0.3573, -1.596, -0.4427, -0.3738, -0.9934, -0.7546, -0.3974, -0.8089, -1.432,
-0.2678, 0.8726, 0.885, 1.088, -0.1851, -0.271, -0.5004, -0.5512, -0.5153, -0.3284, -0.6515, 0.9042, -0.9762, -0.744, -0.3953, 0.1688, 0.5928, 0.9272, 0.6052, 0.7103, -0.3016, -0.1487, 0.2515, 0.2393, 0.2565,
0.3124, 0.8192, 0.1591, -0.6746, -0.8682, -0.7807, -0.7405, -0.7778, 0.3481, 0.8123, 0.8286, 1.155, -1.009, 0.7757, 0.4884, 1.04, 0.3546, 0.1125, 0.1806, 0.3121, -0.4851, -0.9055, -0.9637, -0.2728, -1.26,
-0.5149, 0.2155, 0.9601, 0.8043, 0.6756, 0.7342, 0.4701, 0.9553, 1.608, 0.5156, 1.222, 0.904, -0.0981, -0.823, -0.6382, -1.356, -0.6417, -1.187, -0.8789, -0.916, -1.292, -0.7324, -0.7953, -0.9247, -0.5528,
-0.5288, 0.8585, 0.8561, 0.9089, -0.5485, -1.031, -0.7381, -0.4883, -1.321, -0.2443, -0.5994, 1.332, -1.132, -0.5471, -0.2143, -0.277, 0.3082, 0.5079, 0.7328, 0.6935, 0.1959, 0.6234, 0.4192, 0.2971, -0.1028,
0.3775, 0.5342, 0.6466, -0.6304, -1.083, -1.047, -0.5905, -0.9498, -0.3777, 0.9681, 0.7017, 0.3307, -1.178, 0.392, 0.5717, 0.4838, 0.5245, 0.293, 0.6411, -0.1892, -0.8581, -0.8149, -0.7058, -0.6439, -0.2474,
0.0193, 0.2223, 1.238, 0.7313, 1.227, 0.7637, 1.615, 1.037, 0.7241, 0.9533, 0.9396, 0.358, -0.4311, -0.6526, -0.5332, -1.016, -0.9316, -0.9047, -1.153, -1.652, -1.339, -0.9686, -1.271, -1.032, -0.464,
-0.485, 0.3496, 1.223, 0.2753, 0.3559, -0.6121, -0.2762, -1.151, -1.107, -0.5972, -0.205, 0.5601, -0.5103, -0.4783, -0.8223, -0.4075, 0.7776, 0.9873, 1.529, 0.8427, 0.3131, 0.3724, 0.111, -0.1681, -0.5878,
0.3315, 0.9342, 0.4148, -0.8427, -0.3301, -0.8923, -0.4953, -1.048, -0.1248, 1.286, 0.8288, 1.006, -0.3994, 0.0865, 0.1713, 1.031, 0.3504, 0.5063, -0.0424, -0.3397, -0.1789, -0.7288, -0.9968, -1.394, -1.009,
0.0523, -0.1476, 0.2217, 0.9684, 1.397, 1.063, 1.207, 1.114, 1.784, 0.6864, 1.248, 0.7475, -0.6824, 0.0477, -0.5705, -0.6815, -1.642, -0.7488, -0.7331, -0.9764, -0.4792, -1.285, -1.147, -1.358, -0.4462,
-0.9537, 0.6819, 0.5464, 0.7448, -0.8515, -0.6368, -0.9127, -0.8495, -0.9813, -0.0583, -0.2788, 1.072, -0.8866, -1.052, -0.712, 0.06823, 0.8772, 0.9044, 1.106, 0.8632, 0.5441, 0.2457, 0.724, 0.1297, -0.2173,
0.5992, 0.7762, 0.2094, -0.0139, -1.412, -0.8751, -0.2674, -0.5782, -0.3377, 0.5028, 0.425, 1.065, -0.0815, 0.3245, 0.7141, 1.082, 0.6595, 0.6283, 0.6085, -0.06431, 0.0684, -1.098, -0.4076, -1.22, -0.4714,
0.0484, 0.1239, 0.6632, 1.397, 0.7703, 0.4014, 1.042, 1.536, 1.477, 1.628, 0.7109, 0.6381, -0.7289, -0.2192, -0.7237, -0.5491, -0.8097, -0.9001, -1.177, -0.8599, -0.8234, -0.9596, -0.6691, -0.6669, -0.4975,
-0.4784, 1.263, 0.952, 1.04, -0.5344, -0.5671, -0.7572, -0.7642, -0.9465, -0.9779, -0.6333, 0.9226, -0.3095, -0.6177, -0.9077, 0.4482, 0.843, 0.6304, 1.492, 0.7035, 0.893, -0.3562, 0.1974, 0.2231, 0.2489,
0.5232, 1.372, 0.8861, -0.37, -1.07, -1.249, -0.8652, -1.314, -0.15, -0.0394, 0.5748, 1.172, -0.4937, 0.3658, 0.5371, 0.1571, 1.674, 0.908, 0.644, -0.4627, -0.8093, -1.041, -1.106, -1.301, -1.346,
-0.0338, -0.2782, 0.1648, 0.759, 0.9029, 0.3688, 0.9704, 0.9778, 1.186, 0.2057, 0.8312, 0.2419, -0.7896, -0.2965, -0.5348, -0.4138, -0.6357, -1.023, -1.151, -1.254, -0.8296, -1.295, -0.8237, -0.5314, -1.253,
-0.4994, 0.9685, 1.312, 0.8472, -1.054, -0.8526, -1.119, -1.332, -1.065, -0.4811, -0.7852, 0.4774, -0.3409, -1.171, -0.6996, -0.0103, 1.085, 1.29, 0.5419, 1.034, 0.1304, 0.4402, 0.3242, -0.2903, -0.2345,
], dtype=float, ).reshape((m, k, n))

In [13]:
data

array([[[ 0.7532 ,  0.6916 ,  0.0291 , -0.2289 , -0.998  , -0.9901 ,
         -1.043  , -0.469  , -0.0241 ,  0.6835 ,  0.763  ,  0.8589 ,
         -0.9924 ,  1.038  , -0.1037 ,  0.2255 ,  0.8529 ,  0.2985 ,
          1.057  , -0.06241, -1.18   , -0.6597 , -1.196  , -0.8856 ,
         -1.043  ],
        [-0.5445 ,  0.3736 ,  0.6044 ,  0.6372 ,  0.6475 ,  1.297  ,
          1.058  ,  0.6213 ,  1.024  ,  0.7377 ,  0.7045 ,  0.4956 ,
         -0.9278 , -0.988  , -0.1617 , -0.3001 , -0.7796 , -0.5934 ,
         -1.199  , -1.272  , -0.5313 , -1.049  , -1.382  , -0.6596 ,
         -0.8982 ],
        [-0.7003 ,  0.2911 ,  1.077  ,  0.352  , -0.6711 , -0.3225 ,
         -1.275  , -0.9397 , -0.9861 , -0.6497 , -0.2593 ,  0.2719 ,
         -1.267  , -0.5971 , -0.3543 ,  0.0723 ,  1.254  ,  0.8218 ,
          0.523  ,  0.7268 ,  0.5438 ,  0.4709 ,  0.1534 ,  0.1212 ,
         -0.1881 ]],

       [[ 0.1984 ,  1.073  ,  0.9395 , -0.3283 , -1.068  , -0.6781 ,
         -0.1744 , -0.4396 ,  0.1251 ,  0

In [14]:
def mean() -> np.array:
    return sum(data[i] for i in range(m))/m

M = mean()
M

array([[ 0.36394 ,  0.82234 ,  0.39485 , -0.57969 , -0.8163  , -0.92382 ,
        -0.61849 , -0.73526 , -0.16018 ,  0.656   ,  0.77209 ,  0.98319 ,
        -0.68484 ,  0.53087 ,  0.55317 ,  0.81942 ,  0.73953 ,  0.42333 ,
         0.49444 , -0.062802, -0.67838 , -0.91783 , -0.82976 , -0.84995 ,
        -0.9166  ],
       [-0.17435 ,  0.24895 ,  0.46328 ,  0.96528 ,  0.81227 ,  0.76533 ,
         1.10821 ,  1.08213 ,  1.12712 ,  0.83739 ,  0.86521 ,  0.58276 ,
        -0.42569 , -0.62544 , -0.63656 , -0.63732 , -0.86401 , -1.0218  ,
        -1.0548  , -0.97424 , -0.88224 , -1.00929 , -0.94694 , -0.84438 ,
        -0.94197 ],
       [-0.48035 ,  0.69434 ,  0.95599 ,  0.71972 , -0.52638 , -0.58632 ,
        -0.82201 , -0.85597 , -0.95664 , -0.40759 , -0.45234 ,  0.78502 ,
        -0.60807 , -0.73089 , -0.60956 , -0.071787,  0.79587 ,  0.8757  ,
         0.93059 ,  0.89956 ,  0.28312 ,  0.29828 ,  0.35809 , -0.05674 ,
        -0.15986 ]])

In [15]:
def matrix() -> np.array:
    return sum(
        np.array([
        (data[i, :, j]-M[:, j]).reshape(k,1)
            .dot((data[i, :, j]-M[:, j]).reshape(1,k))
                         for j in range(n)
        ])
               for i in range(m)
               )/(m-1)

CO = matrix()
CO[22]

array([[ 0.12552642, -0.048376  , -0.04336296],
       [-0.048376  ,  0.13967904,  0.04869856],
       [-0.04336296,  0.04869856,  0.08144928]])

In [17]:
def cofunction() -> np.array:
    return sum(np.array([
        np.array([
        (data[i, :, j]-M[:, j]).reshape(k,1)
            .dot((data[i, :, s]-M[:, s]).reshape(1,k))
                         for j in range(n)
        ]) for s in range(n)])
               for i in range(m)
               )/(m-1)

COF = cofunction()
COF[5][11] == COF[11][5].T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])